/** Agent-facing typed operations. All dispatch crosses the same core runtime as UI. */
export const inject=['tools','vaporRuntime'];
export function apply(ctx){
  const str={type:'string'};
  const defs=[
    {name:'media_lab_propose',description:'Record a Lab extraction draft only after inspecting source media using an available tool. Never invent inspection evidence. Include method, coverage evidence and limitations. Text motion descriptions are not executable motion data, and voice descriptions are not cloned voices. Only the user can confirm in Lab.',parameters:{type:'object',additionalProperties:false,required:['commandId','sourceRevisionId','kind','content','method','evidence','limitations'],properties:{commandId:str,sourceRevisionId:str,kind:{type:'string',enum:['image_prompt','video_prompt','motion_description','voice_description']},content:str,method:str,evidence:str,limitations:str}},execute:args=>ctx.vaporRuntime.lab.propose(args)},
    {name:'media_lab_get',description:'Read Lab drafts and user-confirmed results. Use confirmedContent, not original draft, when creating inputs. Pass confirmed IDs as labReferenceIds in media_operation_submit to persist provenance. Confirmation is not paid-generation approval.',parameters:{type:'object',properties:{},additionalProperties:false},execute:()=>({results:ctx.vaporRuntime.lab.list()})},
    {name:'media_operation_submit',description:'Submit an operation to an installed adapter after explicit user intent. Discover its input schema using media_adapters_list first. Only local unpaid adapters are currently allowed. Reuse commandId for uncertain submissions. Results remain pending review.',parameters:{type:'object',additionalProperties:false,required:['commandId','adapterId','artifactId','title','input'],properties:{commandId:str,adapterId:str,artifactId:str,title:str,expectedRevision:str,feedbackId:str,labReferenceIds:{type:'array',maxItems:8,uniqueItems:true,items:str},input:{type:'object'}}},execute:args=>ctx.vaporRuntime.submit(args)},
    {name:'media_adapters_list',description:'List installed executable adapters and their exact input schemas. Capability skills alone are not executable.',parameters:{type:'object',properties:{},additionalProperties:false},execute:()=>({adapters:ctx.vaporRuntime.registry.list()})},
    {name:'media_render_submit',description:'Render a local 720p title card through vapor-remotion. Requires user intent to render or revise; never for a discussion-only request. Maximum 10 seconds, one job at a time. Reuse commandId on uncertain response, and provide expectedRevision plus feedbackId for a feedback-driven revision. This tool returns a durable job, not a finished video.',parameters:{type:'object',additionalProperties:false,required:['commandId','adapterId','artifactId','title','input'],properties:{commandId:str,adapterId:{type:'string',enum:['vapor-remotion']},artifactId:str,title:str,expectedRevision:str,feedbackId:str,input:{type:'object',additionalProperties:false,required:['heading','body','duration','accent'],properties:{heading:str,body:str,duration:{type:'integer',minimum:1,maximum:10},accent:str}}}},execute:args=>ctx.vaporRuntime.submit(args)},
    {name:'media_job_get',description:'Read durable rendering status and exact output revision. A completed render remains pending visual review.',parameters:{type:'object',properties:{id:str},required:['id'],additionalProperties:false},execute:args=>ctx.vaporRuntime.get(args.id)},
    {name:'media_job_cancel',description:'Cancel the specified local render on user request. Retained files and previous revisions are not deleted.',parameters:{type:'object',properties:{id:str},required:['id'],additionalProperties:false},execute:args=>ctx.vaporRuntime.cancel(args.id)}
  ];
  ctx.effect(()=>{const disposers=defs.map(d=>ctx.tools.register({...d,execute:async args=>d.execute(args),output:{schema:{type:'object'},render:(_args,value)=>[{type:'text',text:JSON.stringify(value)}]}}));if(ctx.vaporRuntime.toolkit)disposers.push(ctx.vaporRuntime.toolkit.registerTools(ctx.tools));return()=>disposers.forEach(d=>d());});
}
