/** Durable project catalog and per-request runtime routing. No global selected-project mutation. */
import {AsyncLocalStorage} from 'node:async_hooks';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {mkdirSync,writeFileSync,realpathSync} from 'node:fs';
import {join,basename,extname} from 'node:path';
import {Runtime} from './runtime.js';
import {assert,MIME} from './store.js';
export class Projects {
 constructor(root,catalogRoot){
  mkdirSync(catalogRoot,{recursive:true,mode:0o700});this.catalogRoot=realpathSync(catalogRoot);this.db=new DatabaseSync(join(catalogRoot,'projects.sqlite'));this.db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,root TEXT UNIQUE NOT NULL,title TEXT NOT NULL,brief TEXT NOT NULL DEFAULT "",sessionId TEXT UNIQUE);');
  this.scope=new AsyncLocalStorage();this.runtimes=new Map();this.initializers=new Set();this.pending=new Map();
  const existing=this.db.prepare('SELECT * FROM projects WHERE root=?').get(realpathSync(root));this.defaultId=existing?.id??randomUUID();if(!existing)this.db.prepare('INSERT INTO projects(id,root,title) VALUES(?,?,?)').run(this.defaultId,realpathSync(root),basename(root));
  this.defaultRuntime=this.runtime(this.defaultId);this.facade=this.proxy(()=>this.scope.getStore()??this.defaultRuntime);
 }
 proxy(get){const self=this;return new Proxy({}, {get(_t,key){if(key==='projects')return self;if(key==='forEachProject')return fn=>self.initialize(fn);if(['toolkit','registry','store','lab','services'].includes(key))return self.part(get,key);const v=get()[key];return typeof v==='function'?v.bind(get()):v;}});}
 part(get,key){const self=this;return new Proxy({}, {get(_t,prop){if((key==='toolkit'&&prop==='registerPack')||(key==='registry'&&prop==='register'))return (...args)=>self.initialize(r=>r[key][prop](...args));if(key==='toolkit'&&prop==='registerTools')return tools=>get().toolkit.registerTools.call(self.part(get,'toolkit'),tools);const v=get()[key][prop];return typeof v==='function'?v.bind(get()[key]):v;}});}
 initialize(fn){const entry={fn,disposers:new Map()};try{for(const [id,r]of this.runtimes)entry.disposers.set(id,fn(r));this.initializers.add(entry);}catch(e){for(const d of entry.disposers.values())d?.();throw e;}return async()=>{this.initializers.delete(entry);for(const d of entry.disposers.values())await d?.();};}
 runtime(id){if(this.runtimes.has(id))return this.runtimes.get(id);const p=this.get(id),r=new Runtime(p.root);r.store.db.exec('CREATE TABLE IF NOT EXISTS vapor_project_session(singleton INTEGER PRIMARY KEY CHECK(singleton=1),session_id TEXT NOT NULL); CREATE TABLE IF NOT EXISTS vapor_items(artifact TEXT PRIMARY KEY,category TEXT NOT NULL,group_name TEXT NOT NULL DEFAULT "",pinned INTEGER NOT NULL DEFAULT 0,manual INTEGER NOT NULL DEFAULT 0);');
  if(p.sessionId)r.store.db.prepare('INSERT OR IGNORE INTO vapor_project_session VALUES(1,?)').run(p.sessionId);
  r.projectInfo=()=>this.get(id);this.runtimes.set(id,r);try{for(const e of this.initializers)e.disposers.set(id,e.fn(r));}catch(error){this.runtimes.delete(id);void r.close();throw error;}return r;}
 get(id){const p=this.db.prepare('SELECT * FROM projects WHERE id=?').get(id);assert(p,'项目不存在');return p;}
 list(){return this.db.prepare('SELECT * FROM projects ORDER BY rowid').all();}
 create({title}){assert(typeof title==='string'&&title.trim()&&title.length<=100,'请填写项目名称');const id=randomUUID(),root=join(this.catalogRoot,'projects',id);mkdirSync(root,{recursive:true,mode:0o700});this.db.prepare('INSERT INTO projects(id,root,title) VALUES(?,?,?)').run(id,root,title.trim());return this.get(id);}
 forSession(session){assert(session?.id,'缺少项目聊天');const p=this.db.prepare('SELECT * FROM projects WHERE sessionId=?').get(session.id)??(session.header?.parentSession?this.db.prepare('SELECT * FROM projects WHERE sessionId=?').get(session.header.parentSession):null);assert(p,'请先从左侧打开项目，再继续聊天');return this.runtime(p.id);}
 runSession(session,fn){return this.scope.run(this.forSession(session),fn);}
 async bind(id,sessionId,query){const p=this.get(id);if(p.sessionId){assert(p.sessionId===sessionId,'项目已有固定聊天，请重新打开项目');return p;}
  const records=await query.listSessions(),record=records.find(r=>r.header.id===sessionId);assert(record&&!record.header.parentSession&&record.header.origin!=='subagent','项目聊天不存在');const runtime=this.runtime(id),legacy=runtime.store.snapshot().feedback.some(f=>f.sessionId===sessionId);
  assert(record.header.cwd&&(realpathSync(record.header.cwd)===p.root||id===this.defaultId&&legacy),'聊天与项目不匹配');
  this.db.prepare('UPDATE projects SET sessionId=? WHERE id=? AND sessionId IS NULL').run(sessionId,id);assert(this.get(id).sessionId===sessionId,'项目已在另一个窗口打开，请重试');
  runtime.store.db.prepare('INSERT INTO vapor_project_session VALUES(1,?) ON CONFLICT(singleton) DO UPDATE SET session_id=excluded.session_id').run(sessionId);return this.get(id);
 }
 async open(id,query){if(this.pending.has(id))return this.pending.get(id);const promise=(async()=>{const p=this.get(id);if(p.sessionId)return p;const r=this.runtime(id),old=r.store.db.prepare('SELECT session_id FROM vapor_project_session WHERE singleton=1').get()?.session_id;const records=await query.listSessions();const refs=r.store.snapshot().feedback.map(f=>f.sessionId);const candidates=records.filter(x=>!x.header.parentSession&&x.header.origin!=='subagent'&&(x.header.id===old||refs.includes(x.header.id)||x.header.cwd===p.root));candidates.sort((a,b)=>Number(b.header.id===old)-Number(a.header.id===old)||Number(refs.includes(b.header.id))-Number(refs.includes(a.header.id))||String(b.header.createdAt).localeCompare(String(a.header.createdAt)));return candidates.length?this.bind(id,candidates[0].header.id,query):p;})();this.pending.set(id,promise);try{return await promise;}finally{this.pending.delete(id);}}
 snapshot(id){const p=this.get(id),r=this.runtime(id),items=r.store.snapshot().artifacts.map(a=>({...a,...(r.store.db.prepare('SELECT category,group_name AS groupName,pinned,manual FROM vapor_items WHERE artifact=?').get(a.id)??{category:'outputs',groupName:'',pinned:0,manual:0})}));return {...p,items};}
 update(id,{title,brief}){const p=this.get(id);assert(title===undefined||typeof title==='string'&&title.trim()&&title.length<=100,'项目名称无效');assert(brief===undefined||typeof brief==='string'&&brief.length<=20000,'项目说明过长');this.db.prepare('UPDATE projects SET title=?,brief=? WHERE id=?').run(title?.trim()??p.title,brief??p.brief,id);return this.get(id);}
 organize(id,{artifactId,title,category,groupName='',pinned=false},manual=true){const r=this.runtime(id),a=r.store.snapshot().artifacts.find(a=>a.id===artifactId);assert(a,'素材不存在');assert(['inputs','outputs'].includes(category),'请选择资料或成果');assert(typeof groupName==='string'&&groupName.length<=60&&typeof pinned==='boolean','分组无效');const old=r.store.db.prepare('SELECT manual FROM vapor_items WHERE artifact=?').get(artifactId);assert(manual||!old?.manual,'用户已整理此素材，请尊重现有分组');assert(title===undefined||typeof title==='string'&&title.trim()&&title.length<=200,'名称无效');r.store.transaction(()=>{if(title!==undefined)r.store.db.prepare('UPDATE artifacts SET title=? WHERE id=?').run(title.trim(),artifactId);r.store.db.prepare('INSERT INTO vapor_items VALUES(?,?,?,?,?) ON CONFLICT(artifact) DO UPDATE SET category=excluded.category,group_name=excluded.group_name,pinned=excluded.pinned,manual=excluded.manual').run(artifactId,category,groupName,Number(pinned),Number(manual));r.store.event('artifact.organized',{artifactId});});return this.snapshot(id);}
 deleteArtifact(id,{artifactId}){const r=this.runtime(id);assert(r.store.db.prepare('SELECT id FROM artifacts WHERE id=?').get(artifactId),'素材不存在');r.store.transaction(()=>{r.store.db.prepare('INSERT OR IGNORE INTO vapor_deleted VALUES(?)').run(artifactId);r.store.event('artifact.deleted',{artifactId});});return this.snapshot(id);}
 import(id,name,bytes){assert(typeof name==='string'&&name.length<=255&&!/[\\/\x00]/.test(name),'文件名无效');const ext=extname(name).toLowerCase();assert(MIME[ext],'暂不支持此文件格式');assert(bytes.length>0&&bytes.length<=512*1024*1024,'文件为空或超过 512 MB');const r=this.runtime(id),aid=randomUUID(),dir=join(r.root,'inputs',aid);mkdirSync(dir,{recursive:true,mode:0o700});const path=join(dir,name);writeFileSync(path,bytes,{flag:'wx',mode:0o600});const revision=r.store.register({id:aid,title:name,path:join('inputs',aid,name)});this.organize(id,{artifactId:aid,category:'inputs'},false);return {artifactId:aid,revision};}
 async close(){for(const r of this.runtimes.values())await r.close();this.db.close();}
}
