import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Runtime} from '../runtime.js';
import {ProjectContext,readHistory} from '../context.js';
import {apply} from '../context-tools.js';
function session(root,id='main'){const events=[];return {id,header:{cwd:root},get seq(){return events.length;},snapshotEvents(from=0){return events.slice(from);},append(type,data){const e={seq:events.length,type,data};events.push(e);return e;}};}
async function fixture(t){const root=mkdtempSync(join(tmpdir(),'vapor-context-')),runtime=new Runtime(root);t.after(async()=>{await runtime.close();rmSync(root,{recursive:true,force:true});});const context=new ProjectContext(runtime);runtime.store.db.prepare('INSERT INTO vapor_project_session VALUES(1,?)').run('main');return {root,runtime,context,session:session(root)};}
test('one main session per project, no arbitrary session or cross-project binding',async t=>{const f=await fixture(t);assert.equal(f.context.bind(f.session),'main');assert.throws(()=>f.context.bind(session(f.root,'other')),/main session/);assert.throws(()=>f.context.bind(session(tmpdir())),/workspace/);const child=session(f.root);child.header.parentSession='parent';assert.throws(()=>f.context.bind(child),/Main project/);assert.equal(new ProjectContext(f.runtime).primary(),'main');});
test('fifteen compactions rehydrate authoritative revisions and pending budget without losing raw evidence',async t=>{
 const f=await fixture(t);writeFileSync(join(f.root,'asset.txt'),'original');f.runtime.store.register({id:'take',title:'Take',path:'asset.txt'});mkdirSync(join(f.root,'generation'));writeFileSync(join(f.root,'generation/ledger.json'),JSON.stringify({budgetUSD:10,jobs:{paid:{state:'submission_unknown',reservedUSD:2,actualUSD:null}}}));
 const original=f.session.append('user/message',{content:[{type:'text',text:'Keep the blue palette. Reject red. Approved revision: take-v1.'}]});
 let notice=f.context.notice(f.session);assert.ok(notice);f.session.append('user/message',notice);assert.equal(f.context.notice(f.session),null);
 for(let i=0;i<15;i++){f.session.append('compaction/end',{id:'compact-'+i});notice=f.context.notice(f.session);assert.ok(notice);assert.ok(notice.content[0].text.length<12000);const state=f.context.state();assert.equal(state.ledger.unknownCount,1);assert.equal(state.ledger.unsettledReservedUSD,2);assert.equal(state.assets.recent[0].id,'take');f.session.append('user/message',notice);assert.equal(f.context.notice(f.session),null);}
 const query={readEvent:async r=>{assert.equal(r.sessionId,'main');return {session:{id:'main'},target:original};}};const recalled=await readHistory(query,f.session,{seq:0});assert.match(recalled.text,/Reject red/);assert.equal(recalled.nextOffset,null);assert.equal(f.session.snapshotEvents()[0],original);
});
test('discarded step context retries; changes and restarts refresh state',async t=>{const f=await fixture(t);const n=f.context.notice(f.session);assert.ok(f.context.notice(f.session));f.session.append('user/message',f.context.notice(f.session));assert.equal(f.context.notice(f.session),null);writeFileSync(join(f.root,'project.json'),JSON.stringify({project:{brief:'New goal'}}));assert.match(f.context.notice(f.session).content[0].text,/New goal/);assert.ok(new ProjectContext(f.runtime).notice(f.session));});
test('original history pagination is Unicode-safe and excludes request envelopes',async t=>{const f=await fixture(t);const text='图'.repeat(4500);const q={readEvent:async()=>({session:{id:'main'},target:{type:'tool/result',data:{message:{content:[{type:'text',text}]}}}})};const a=await readHistory(q,f.session,{seq:0});const b=await readHistory(q,f.session,{seq:0,offset:a.nextOffset});assert.equal(a.text+b.text,text);assert.equal(b.nextOffset,null);await assert.rejects(()=>readHistory(q,f.session,{seq:-1}),/sequence/);await assert.rejects(()=>readHistory({readEvent:async()=>({session:{id:'main'},target:{type:'request/header',data:{secret:'never'}}})},f.session,{seq:0}),/excluded/);await assert.rejects(()=>readHistory({readEvent:async()=>({session:{id:'other'},target:{}})},f.session,{seq:0}),/scope/);});
test('preset hook adds bounded state after compaction middleware and search is owning-session only',async t=>{const f=await fixture(t),registered=new Map();let hook,dispose,request;
 apply({vaporRuntime:f.runtime,tools:{register:d=>{registered.set(d.name,d);return()=>registered.delete(d.name);}},sessionQuery:{searchEvents:async r=>{request=r;return {session:{id:r.sessionId},items:[{seq:0,type:'user/message',surface:'shadowed',snippet:'blue'}]};}},on:(name,fn)=>{assert.equal(name,'agent/pre-step');hook=fn;return()=>{};},effect:fn=>{dispose=fn();}});t.after(()=>dispose());
 const decision=await hook({agent:{session:f.session},signal:new AbortController().signal},async()=>{f.session.append('compaction/end',{});return {kind:'enter',messages:[]};});assert.equal(decision.messages.length,1);assert.equal(decision.messages[0].source.form,'notice');
 await registered.get('media_history_search').execute({query:'blue'},{agent:{session:f.session}});assert.deepEqual(request,{sessionId:'main',query:'blue',limit:8});assert.equal(registered.size,5);
});
