import {test} from 'node:test';import assert from 'node:assert/strict';import {Hub} from '../hub.js';
const record={packageName:'@toddzheng024/vapor',versions:[{version:'0.3.0',source:{installSpec:'@toddzheng024/vapor@0.3.0'}}],security:{status:'passed'}};
test('planning uses read-only resolve and exact non-yanked version',async()=>{const calls=[],hub=new Hub({request:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>record};}});const p=await hub.plan({name:record.packageName,version:'0.3.0'});assert.equal(p.input.installSpec,'@toddzheng024/vapor@0.3.0');assert(calls[0].url.includes('/packages/resolve?name='));assert.equal(calls[0].options.body,undefined);assert.equal(calls[0].options.redirect,'error');await assert.rejects(hub.plan({name:'--help',version:'0.3.0'}));await assert.rejects(hub.plan({name:record.packageName,version:'latest'}));await assert.rejects(hub.plan({name:record.packageName,version:'0.4.0'}));});
test('search tolerates additive metadata but validates required fields',async()=>{const hub=new Hub({request:async()=>({ok:true,json:async()=>({items:[{packageName:'vapor',latestVersion:'0.3.0',security:{status:'passed'},newField:true},{packageName:123}]})})});const data=await hub.search({query:'vapor'});assert.equal(data.items.length,1);assert.equal(data.items[0].packageName,'vapor');});
test('withdrawn version cannot be planned',async()=>{const hub=new Hub({request:async()=>({ok:true,json:async()=>({...record,versions:[{...record.versions[0],yanked:true}]})})});await assert.rejects(hub.plan({name:record.packageName,version:'0.3.0'}));});
test('post-install check rejects overridden versions and missing bundle activation',async()=>{
 const {mkdtempSync,mkdirSync,writeFileSync}=await import('node:fs'),{join}=await import('node:path'),{tmpdir}=await import('node:os'),{verifyInstalledVersion}=await import('../hub.js');const root=mkdtempSync(join(tmpdir(),'vapor-version-'));mkdirSync(join(root,'node_modules/plugin'),{recursive:true});writeFileSync(join(root,'node_modules/plugin/package.json'),JSON.stringify({name:'plugin',version:'1.0.0'}));writeFileSync(join(root,'package.json'),JSON.stringify({dsh:{profile:{bundles:['plugin']}}}));assert.equal(verifyInstalledVersion(root,'plugin','1.0.0'),true);assert.throws(()=>verifyInstalledVersion(root,'plugin','2.0.0'));writeFileSync(join(root,'package.json'),'{}');assert.throws(()=>verifyInstalledVersion(root,'plugin','1.0.0'));
});
test('install plan distinguishes a new installation from installed version without changing it',async()=>{
 const {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync}=await import('node:fs'),{join}=await import('node:path'),{tmpdir}=await import('node:os');const home=mkdtempSync(join(tmpdir(),'vapor-plan-installed-'));
 try{const hub=new Hub({home,request:async()=>({ok:true,json:async()=>record})}),args={name:record.packageName,version:'0.3.0'};assert.equal((await hub.plan(args)).installedVersion,undefined);const dir=join(home,'profiles/web/node_modules',record.packageName);mkdirSync(dir,{recursive:true});const file=join(dir,'package.json'),original=JSON.stringify({name:record.packageName,version:'0.2.0'});writeFileSync(file,original);assert.equal((await hub.plan(args)).installedVersion,'0.2.0');assert.equal(readFileSync(file,'utf8'),original);}finally{rmSync(home,{recursive:true,force:true});}
});
