import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,renameSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {ProfileUpdate} from '../profile-update.js';
function fixture(){const home=mkdtempSync(join(tmpdir(),'vapor-update-'));mkdirSync(join(home,'profiles/web'),{recursive:true});writeFileSync(join(home,'profiles/web/package.json'),'old');return new ProfileUpdate(home,'web');}
test('failed staged install leaves active profile untouched',async()=>{const u=fixture();await assert.rejects(u.stage(async name=>{writeFileSync(join(u.root,name,'package.json'),'broken');throw Error('failure');}));assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'old');assert.equal(u.read().state,'failed');});
test('successful update waits until startup and retains previous profile',async()=>{const u=fixture();const r=await u.stage(async name=>writeFileSync(join(u.root,name,'package.json'),'new'));assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'old');u.activate();assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'new');assert.equal(readFileSync(join(u.root,r.backupName,'package.json'),'utf8'),'old');});
test('startup recovers crash between directory renames',async()=>{const u=fixture();const r=await u.stage(async name=>writeFileSync(join(u.root,name,'package.json'),'new'));r.state='switching';u.write(r);renameSync(u.target,join(u.root,r.backupName));u.activate();assert.equal(u.read().state,'applied');assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'new');});
test('changed active configuration prevents stale update activation',async()=>{const u=fixture();await u.stage(async name=>writeFileSync(join(u.root,name,'package.json'),'new'));writeFileSync(join(u.target,'package.json'),'user edit');assert.equal(u.activate().state,'failed');assert.equal(u.activate().state,'failed');assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'user edit');await u.stage(async name=>writeFileSync(join(u.root,name,'package.json'),'fresh update'));assert.equal(u.activate().state,'applied');});
test('rollback is staged and restores previous profile only at startup',async()=>{const u=fixture();await u.stage(async name=>writeFileSync(join(u.root,name,'package.json'),'new'));u.activate();await u.rollback();assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'new');u.activate();assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'old');assert.equal(u.read().state,'applied');});
test('separate updater instances cannot stage or activate concurrently',async()=>{const u=fixture(),other=new ProfileUpdate(u.home,'web');let release;const wait=new Promise(r=>release=r);const work=u.stage(async()=>wait);await assert.rejects(other.stage(async()=>{}));assert.throws(()=>other.activate());release();await work;assert.equal(u.read().state,'ready');});

test('missing staged files cancel update without preventing current profile startup',async()=>{const u=fixture();const r=await u.stage(async()=>{});renameSync(join(u.root,r.stageName),join(u.root,r.stageName+'-missing'));assert.equal(u.activate().state,'failed');assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'old');assert.equal(u.activate().state,'failed');});
test('corrupted replacement is retained separately and verified backup restores on startup',async()=>{const u=fixture(),r=await u.stage(async name=>writeFileSync(join(u.root,name,'package.json'),'new'));r.state='switching';u.write(r);renameSync(u.target,join(u.root,r.backupName));renameSync(join(u.root,r.stageName),u.target);writeFileSync(join(u.target,'package.json'),'corrupt');assert.equal(u.activate().state,'rolled_back');assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'old');});
test('unverified backup fails closed and cannot be overwritten by another update',async()=>{const u=fixture(),r=await u.stage(async()=>{});r.state='recovery_required';u.write(r);await assert.rejects(u.stage(async()=>{}));assert.throws(()=>u.activate(),/旧版本校验失败/);assert.equal(u.read().state,'recovery_required');assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'old');});
test('restart finishes interrupted restoration after original directory was restored',async()=>{const u=fixture(),r=await u.stage(async()=>{});r.state='restoring';u.write(r);assert.equal(u.activate().state,'rolled_back');assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'old');});
test('profiles keep independent prepared updates and rollback histories',async()=>{
 const a=fixture();mkdirSync(join(a.root,'studio'));writeFileSync(join(a.root,'studio/package.json'),'studio-old');const b=new ProfileUpdate(a.home,'studio');
 await a.stage(async name=>writeFileSync(join(a.root,name,'package.json'),'web-new'));
 await b.stage(async name=>writeFileSync(join(b.root,name,'package.json'),'studio-new'));
 assert.equal(a.read().profile,'web');assert.equal(b.read().profile,'studio');a.activate();b.activate();await a.rollback();a.activate();assert.equal(readFileSync(join(a.target,'package.json'),'utf8'),'old');assert.equal(readFileSync(join(b.target,'package.json'),'utf8'),'studio-new');assert.equal(b.read().state,'applied');
});
test('legacy record belongs only to its profile and migrates on next write',async()=>{
 const u=fixture(),r=await u.stage(async name=>writeFileSync(join(u.root,name,'package.json'),'new'));renameSync(u.record,u.legacyRecord);const other=new ProfileUpdate(u.home,'studio');assert.equal(other.read(),null);assert.equal(other.activate(),null);assert.equal(u.activate().state,'applied');assert.equal(JSON.parse(readFileSync(u.record)).state,'applied');assert.equal(JSON.parse(readFileSync(u.legacyRecord)).id,r.id);
});
test('cancel prepared update leaves current files intact and allows a fresh plan',async()=>{const u=fixture();await u.stage(async name=>writeFileSync(join(u.root,name,'package.json'),'new'));assert.equal(u.cancel().state,'cancelled');assert.equal(u.activate().state,'cancelled');assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'old');await u.stage(async name=>writeFileSync(join(u.root,name,'package.json'),'fresh'));assert.equal(u.activate().state,'applied');assert.throws(()=>u.cancel());assert.equal(readFileSync(join(u.target,'package.json'),'utf8'),'fresh');});
