import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Projects} from '../projects.js';
async function fixture(t){const dir=mkdtempSync(join(tmpdir(),'vapor-projects-')),root=join(dir,'original');mkdirSync(root);const projects=new Projects(root,join(dir,'catalog'));t.after(async()=>{await projects.close();rmSync(dir,{recursive:true,force:true});});return {projects,dir};}
test('opening binds one existing session and rejects cross-project binding',async t=>{const {projects:p}=await fixture(t),a=p.get(p.defaultId),q={listSessions:async()=>[{header:{id:'old',cwd:a.root,createdAt:1}}]};assert.equal((await p.open(a.id,q)).sessionId,'old');assert.equal((await p.open(a.id,q)).sessionId,'old');await assert.rejects(()=>p.bind(a.id,'new',q),/固定聊天/);const b=p.create({title:'第二个项目'});await assert.rejects(()=>p.bind(b.id,'old',q),/不匹配/);assert.equal(p.forSession({id:'old',header:{cwd:a.root}}).root,a.root);assert.throws(()=>p.forSession({id:'unknown'}),/左侧/);});
test('parallel project tools retain roots, packs and independent activation',async t=>{const {projects:p}=await fixture(t),a=p.get(p.defaultId),b=p.create({title:'B'});const definitions=[{id:'test.read',description:'test',required:[],fields:{}}];p.facade.toolkit.registerPack('vapor-test','/tmp',definitions);const records=[{header:{id:'a',cwd:a.root}},{header:{id:'b',cwd:b.root}}],q={listSessions:async()=>records};await p.bind(a.id,'a',q);await p.bind(b.id,'b',q);const collected=await Promise.all(['a','b'].map(id=>p.runSession({id},async()=>{await new Promise(r=>setTimeout(r,id==='a'?10:1));return p.facade.toolkit.writeDocument({commandId:'same',name:'script.txt',content:id});})));assert.equal(readFileSync(join(a.root,collected[0].path),'utf8'),'a');assert.equal(readFileSync(join(b.root,collected[1].path),'utf8'),'b');assert.equal(p.runtime(a.id).toolkit.list().length,1);p.runtime(b.id).toolkit.setEnabled({name:'vapor-test',enabled:false});assert.equal(p.runtime(a.id).toolkit.list().length,1);assert.equal(p.runtime(b.id).toolkit.list().length,0);});
test('imports preserve originals, categorize inputs and respect manual organization',async t=>{const {projects:p}=await fixture(t),id=p.defaultId;const one=p.import(id,'剧本.md',Buffer.from('原稿')),two=p.import(id,'剧本.md',Buffer.from('新稿'));assert.notEqual(one.artifactId,two.artifactId);assert.equal(p.snapshot(id).items.length,2);assert.equal(p.snapshot(id).items[0].category,'inputs');p.organize(id,{artifactId:one.artifactId,category:'inputs',groupName:'剧本'},false);p.organize(id,{artifactId:one.artifactId,category:'inputs',groupName:'我的原稿',pinned:true,title:'用户命名'});assert.throws(()=>p.organize(id,{artifactId:one.artifactId,category:'outputs'},false),/用户已整理/);p.runtime(id).store.register({id:one.artifactId,title:'Agent 标题',path:two.revision.source,expectedRevision:one.revision.id});assert.equal(p.snapshot(id).items.find(a=>a.id===one.artifactId).title,'用户命名');assert.equal(readFileSync(p.runtime(id).store.file(one.revision.id).absolute,'utf8'),'原稿');assert.throws(()=>p.import(id,'../escape.md',Buffer.from('bad')),/文件名/);const b=p.create({title:'B'});assert.throws(()=>p.organize(b.id,{artifactId:one.artifactId,category:'inputs'}),/不存在/);p.update(id,{brief:'保持蓝色风格'});assert.equal(p.runtime(id).projectInfo().brief,'保持蓝色风格');});
test('project context must be bound by open flow, never first model step',async t=>{const {projects:p}=await fixture(t);const {ProjectContext}=await import('../context.js');const context=new ProjectContext(p.defaultRuntime);assert.throws(()=>context.bind({id:'rogue',header:{cwd:p.defaultRuntime.root}}),/main session/);assert.equal(context.primary(),null);});
test('bound session, brief and manual groups survive catalog/runtime restart',async t=>{const dir=mkdtempSync(join(tmpdir(),'vapor-restart-')),root=join(dir,'root');mkdirSync(root);let p=new Projects(root,join(dir,'catalog'));t.after(async()=>{await p.close();rmSync(dir,{recursive:true,force:true});});const id=p.defaultId;await p.bind(id,'fixed',{listSessions:async()=>[{header:{id:'fixed',cwd:root}}]});const asset=p.import(id,'draft.txt',Buffer.from('keep original'));p.organize(id,{artifactId:asset.artifactId,category:'inputs',groupName:'剧本',pinned:true});p.update(id,{title:'片名',brief:'蓝色风格'});await p.close();p=new Projects(root,join(dir,'catalog'));assert.equal(p.get(id).sessionId,'fixed');assert.equal(p.snapshot(id).items[0].groupName,'剧本');assert.equal(p.get(id).brief,'蓝色风格');assert.equal(p.forSession({id:'fixed'}).root,p.get(id).root);});
test('registered tool closures dispatch to the owning project, not registration-time default',async t=>{const {projects:p}=await fixture(t),a=p.get(p.defaultId),b=p.create({title:'B'}),q={listSessions:async()=>[{header:{id:'a',cwd:a.root}},{header:{id:'b',cwd:b.root}}]};await p.bind(a.id,'a',q);await p.bind(b.id,'b',q);const defs=new Map();p.facade.toolkit.registerTools({register:d=>{defs.set(d.name,d);return()=>{};}});await Promise.all(['a','b'].map(id=>p.runSession({id},()=>defs.get('media_document_write').execute({commandId:'same',name:'script.txt',content:id}))));assert.equal(readFileSync(join(a.root,'inputs/script.txt'),'utf8'),'a');assert.equal(readFileSync(join(b.root,'inputs/script.txt'),'utf8'),'b');});
test('deleting an artifact removes it from project and canvas but preserves original versions',async t=>{const {projects:p}=await fixture(t),id=p.defaultId,asset=p.import(id,'keep.txt',Buffer.from('original'));const {Canvas}=await import('../canvas.js');const c=new Canvas(p.runtime(id).store);c.update({items:[{id:asset.artifactId,kind:'artifact',title:'keep',x:0,y:0,w:300,h:200}]});const b=p.create({title:'B'});assert.throws(()=>p.deleteArtifact(b.id,{artifactId:asset.artifactId}),/不存在/);p.deleteArtifact(id,{artifactId:asset.artifactId});assert.equal(p.snapshot(id).items.length,0);assert.equal(c.snapshot().length,0);assert.equal(readFileSync(p.runtime(id).store.file(asset.revision.id).absolute,'utf8'),'original');p.deleteArtifact(id,{artifactId:asset.artifactId});});
