import {mountPlugins} from './plugins.js';
/** Capability-driven forms. Polling preserves unfinished inputs and approval forms. */
export function mountToolkit({el,api,fileURL,container,refresh,pluginContainer=container,jobsOnly=false}){
 const renderPlugins=mountPlugins({el,api,container:pluginContainer,refresh});
 const panel=el('section',{'aria-label':'创作工具'}),select=el('select',{'aria-label':'选择工具'}),fields=el('div'),help=el('p'),message=el('p',{role:'status'}),jobs=el('div');
 let plugins=[],operations=[],command=null,opSignature='';const rows=new Map(),drafts=new Map();
 const labels={project:'项目说明文件',manifest:'制作清单文件',plan:'任务计划文件',source:'来源',audio:'音频文件',video:'视频文件',picture:'画面文件',alignment:'字幕对齐文件',transcript:'转写',textFile:'合成文本文件',sourceNote:'来源与使用说明',promptFile:'提示词或来源说明文件',name:'声音档案名称',title:'标题',start:'开始秒',end:'结束秒',duration:'时长秒',budgetUSD:'项目总预算 USD',estimatedUSD:'预估费用 USD',reservedUSD:'预留费用 USD',pricingSource:'费用估算依据',priceValidThrough:'价格有效截止日',authorizationNote:'授权说明'};
 function change(){fields.replaceChildren();command=null;const o=operations.find(x=>x.id===select.value);if(!o){help.textContent='当前没有启用的工具，请在创作能力中启用所需能力。';return;}help.textContent=`${o.remote?'需要用户批准上传或远程执行':'本地执行'}。文件路径相对当前项目目录；输入素材会保留。`;
  for(const [name,s]of Object.entries(o.inputSchema.properties)){const input=s.enum?el('select',{},...s.enum.map(v=>el('option',{value:v,text:v}))):el(s.type==='array'?'textarea':'input',{type:s.type==='boolean'?'checkbox':['integer','number'].includes(s.type)?'number':'text'});input.dataset.field=name;if(s.minimum!==undefined)input.min=s.minimum;if(s.maximum!==undefined)input.max=s.maximum;if(s.type==='number')input.step='any';input.addEventListener('input',()=>command=null);fields.append(el('label',{},(labels[name]||name)+(o.inputSchema.required.includes(name)?' *':'')+(s.type==='array'?'（每行一项）':''),input));}
 }
 select.addEventListener('change',change);
 const prepare=el('button',{text:'准备任务',onclick:async()=>{prepare.disabled=true;try{const o=operations.find(x=>x.id===select.value),input={};for(const node of fields.querySelectorAll('[data-field]')){const k=node.dataset.field,s=o.inputSchema.properties[k];if(s.type==='boolean')input[k]=node.checked;else if(node.value!=='')input[k]=s.type==='array'?node.value.split('\n').filter(Boolean).map(v=>s.items.type==='number'?Number(v):v):['number','integer'].includes(s.type)?Number(node.value):node.value;}command??=crypto.randomUUID();await api('/toolkit/prepare',{commandId:command,operation:o.id,input});command=null;await refresh();message.textContent='任务已准备，可在下面查看输入并执行。';}catch(e){message.textContent=e.message;}finally{prepare.disabled=false;}}});
 if(jobsOnly)panel.append(el('h2',{text:'创作任务'}),message,jobs);else panel.append(el('h2',{text:'创作工具'}),select,help,fields,prepare,message,jobs);container.append(panel);
 const button=(title,fn,error)=>el('button',{text:title,onclick:async event=>{event.target.disabled=true;try{await fn();await refresh();}catch(e){error.textContent=e.message;}finally{event.target.disabled=false;}}});
 function row(j){const disabled=plugins.some(p=>!p.enabled&&p.operations.some(o=>o.id===j.operation));const box=el('div',{class:'job'}),error=el('p',{role:'status',text:j.error||''});box.append(el('h3',{text:`${operations.find(o=>o.id===j.operation)?.description||'创作任务'} · ${{prepared:'准备就绪',awaiting_approval:'待你确认',running:'处理中',submitted:'已提交',completed:'已完成',failed:'未完成',cancelled:'已取消',recovery_required:'需要处理'}[j.state]||'等待处理'}`}),el('details',{},el('summary',{text:'任务编号'}),el('p',{text:j.id})),el('details',{},el('summary',{text:'查看本次输入与来源文件'}),el('pre',{text:JSON.stringify({input:j.input,files:j.inputs,plan:j.plan},null,2)})));
  if(disabled)box.append(el('p',{text:'所属插件已停用，重新启用后可执行；历史记录和原请求恢复保留。'}));
  if(j.state==='prepared'&&!disabled)box.append(button('执行本地任务',()=>api('/toolkit/run',{id:j.id}),error));
  if(j.state==='awaiting_approval'&&!disabled){
   const draftKey=j.id+':'+j.fingerprint,saved=drafts.get(draftKey)||{},remember=(key,value)=>drafts.set(draftKey,{...drafts.get(draftKey),[key]:value});
   const inputs={},names=j.remote&&j.remote!=='download'?['budgetUSD','estimatedUSD','reservedUSD','pricingSource','priceValidThrough','authorizationNote']:['authorizationNote'];
   for(const name of names){const input=el('input',{type:name.endsWith('USD')?'number':name==='priceValidThrough'?'date':'text','aria-label':labels[name],...(name==='budgetUSD'&&j.budgetUSD?{value:j.budgetUSD}:{})});if(name.endsWith('USD')){input.min='0';input.step='.01';}if(saved[name]!==undefined)input.value=saved[name];input.addEventListener('input',()=>remember(name,input.value));inputs[name]=input;box.append(el('label',{},labels[name],input));}
   const confirmed=el('input',{type:'checkbox'});confirmed.checked=saved.confirmed===true;confirmed.addEventListener('change',()=>remember('confirmed',confirmed.checked));box.append(el('label',{},confirmed,'我确认本次输入、执行内容及费用（如有）'),button('批准并执行本次任务',()=>{const data={id:j.id,fingerprint:j.fingerprint,confirmed:confirmed.checked};for(const [key,input]of Object.entries(inputs)){if(!input.value.trim())throw new Error('请填写'+labels[key]);data[key]=key.endsWith('USD')?Number(input.value):input.value;}return api('/toolkit/approve',data);},error));
  }
  if(['prepared','awaiting_approval'].includes(j.state)&&j.cloudSubmitted===false)box.append(button('取消本次任务',()=>api('/toolkit/cancel',{id:j.id}),error));
  if(['submitted','recovery_required'].includes(j.state)&&['ledger','viggle','download'].includes(j.remote))box.append(button(j.remote==='download'?'继续原下载 / 查询':'查询并取回原任务',()=>api('/toolkit/resume',{id:j.id}),error));
  if(j.remote&&j.authorization&&j.remote!=='download'){
   const detail=el('details',{},el('summary',{text:'恢复、对账与实际费用'})),action=el('select',{},...['status','reconcile','settle','mark-terminal'].map(v=>el('option',{value:v,text:{status:'查看账本',reconcile:'关联核实的原请求',settle:'登记实际费用','mark-terminal':'登记远端已失败或取消'}[v]}))),data={};
   for(const [key,title]of [['providerJobId','原任务 ID（多任务计划必填）'],['callId','原 Modal call ID / Viggle remote ID'],['requestFile','原 fal 请求凭据 JSON 文件路径'],['evidence','核实证据'],['actualUSD','实际费用 USD'],['state','远端终态：failed 或 cancelled']]){const input=el('input',{'aria-label':title});data[key]=input;detail.append(el('label',{},title,input));}
   detail.append(action,el('p',{text:'登记终态不会取消远端计算。先在服务商控制台操作并核实；未知提交不能换 ID 重试。'}),button('执行所选恢复操作',()=>{const value={id:j.id,action:action.value};for(const [k,n]of Object.entries(data))if(n.value.trim())value[k]=k==='actualUSD'?Number(n.value):n.value;return api('/toolkit/recover',value);},error));box.append(detail);if(j.recovery)box.append(el('details',{},el('summary',{text:'最近一次对账结果'}),el('pre',{text:JSON.stringify(j.recovery,null,2)})));
  }
  for(const out of j.outputs)box.append(el('p',{},el('a',{href:fileURL(out.revisionId),target:'_blank',rel:'noopener',text:out.path.split('/').at(-1)})));
  box.append(el('p',{text:'完成后请预览作品，确认画面和声音符合你的期待。'}),error);return box;
 }
 return state=>{renderPlugins(state);const data=state.toolkit;panel.hidden=!data;if(!data)return;plugins=data.plugins||[];operations=data.operations;const sig=JSON.stringify(operations);if(sig!==opSignature){opSignature=sig;const previous=select.value;select.replaceChildren(...operations.map(o=>el('option',{value:o.id,text:o.description})));if(operations.some(o=>o.id===previous))select.value=previous;change();}prepare.disabled=data.busy||!operations.length;for(const j of data.jobs){const signature=JSON.stringify([j,plugins.filter(p=>p.operations.some(o=>o.id===j.operation)).map(p=>[p.name,p.enabled])]),old=rows.get(j.id);if(old?.signature===signature)continue;const box=row(j);if(old)old.box.replaceWith(box);else jobs.prepend(box);rows.set(j.id,{box,signature});}};
}
